import Head from "next/head";
import { type NextPage } from "next";
import { Suspense } from "react";
import { Spinner } from "@/components/ui/Spinner";
import { Hero, StoreNav } from "@/components";
const Home: NextPage = () => {
  return (
    <Suspense fallback={<Spinner />}>
      <Head>
        <title>CS Store Argentina</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen justify-center bg-white">
        <StoreNav />
        <div className="flex h-full w-full justify-center">
          <div className="flex w-11/12 flex-col md:w-3/4">
            <Hero />
          </div>
        </div>
      </main>
    </Suspense>
  );
};

export default Home;
