import { type NextPage } from "next";
import Head from "next/head";
import { api } from "@/utils/api";
import { useSession } from "next-auth/react";
import { AuthNavbar, Carousel, Navbar } from "@/components";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center bg-white">
        <div className="flex w-11/12 flex-col md:w-3/4">
          {sessionData ? <AuthNavbar sessionData={sessionData} /> : <Navbar />}
          <Carousel />
          <AuthShowcase />
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex min-h-min flex-col items-center justify-center gap-4 px-4">
      <p className="text-center text-2xl text-gray-500 ">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
    </div>
  );
};
